environment:
  CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
  matrix:
    - TARGET_ARCH: x64
      PY: 3.7

platform:
    - x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    # The AppVeyor 'rollout builds' option is supposed to serve the same
    # purpose but it is problematic because it tends to cancel builds pushed
    # directly to master instead of just PR builds (or the converse).
    # credits: JuliaLang developers.
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
         https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
         Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
           throw "There are newer queued builds for this pull request, failing early." }

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    - cmd: conda update conda --quiet
    - cmd: conda config --add channels conda-forge --force

    - cmd: set PYTHONUNBUFFERED=1

    - cmd: conda create --name TEST python=%PY% --file requirements.txt --file requirements-dev.txt
    - cmd: conda activate TEST
    - cmd: conda info --all
    - cmd: conda list

# Skip .NET project specific build phase.
build: off

test_script:
    - pytest -n 2 -rxs --cov=ctd tests
    - pytest -s -rxs --doctest-modules -vv ctd
