language: python

sudo: false

addons:
  apt:
    packages:
      - xvfb

env:
  global:
    - secure: "HmQVTgIORmOdQCInEJ5b62zsFXOYUfeNChkdmxbsL8N6eUj+QEXRLkZvedUHinzCjRRG38kkXPtp6EpUgv19bEO+0A3WCNqCP7Eqy0WwasjTGxC8QRX5ZBjpojPNlT7COCdFpTCBf/w/kTLM5xT9SH01uUF8ETpfBtF057VkP+0="lfkVl2pv95UMOXmtlBxYOr9H/QCwWEezWH4lfmvKR8f4="

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

matrix:
  fast_finish: true
  include:
    - name: "default"
      env: PY=3.7
    - name: "doctest"
      env: PY=3.7
    - name: "coding_standards"
      env: PY=3.7
    - name: "docs"
      env: PY=3.7

before_install:
  # Install miniconda and create TEST env.
  - |
    wget http://bit.ly/miniconda -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda --quiet
    conda install pycryptosat --quiet
    conda config --add channels conda-forge --force
    conda config --set sat_solver pycryptosat
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
    source activate TEST

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install --no-deps --force-reinstall ctd-${version}.tar.gz && popd

script:
  - if [[ $TRAVIS_JOB_NAME == "default" ]]; then
      cp -r tests/ /tmp ;
      pushd /tmp && pytest -n 2 -rxs --cov=ctd tests && popd ;
    fi

  - if [[ $TRAVIS_JOB_NAME == "doctest" ]]; then
      pytest -s -rxs --doctest-modules -vv ctd ;
    fi

  - if [[ $TRAVIS_JOB_NAME == 'coding_standards' ]]; then
      pytest --flake8 -m flake8 ;
    fi
  
  - |
    if [[ $TRAVIS_JOB_NAME == 'docs' ]]; then
      set -e
      cp notebooks/quick_intro.ipynb docs/source/
      pushd docs
      make clean html linkcheck
      popd
      if [[ -z "$TRAVIS_TAG" ]]; then 
        python -m doctr deploy --build-tags --key-path github_deploy_key_pyoceans_python_ctd.enc --built-docs docs/build/html/ dev
      else
        python -m doctr deploy --build-tags --key-path github_deploy_key_pyoceans_python_ctd.enc --built-docs docs/build/html/ "version-$TRAVIS_TAG"
        python -m doctr deploy --build-tags --key-path github_deploy_key_pyoceans_python_ctd.enc --built-docs docs/build/html/ .
      fi
    fi

doctr:
  require-master: true
  sync: false

deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: "PQK/Hsl7DrIG4ZE6cpGJ4C8xOiI3bDw12Ont5RIgdMgPbqj+QZAMN88mUdv7EZvGRI8QQSWMF+y4Ehji1KZotRMGHTfBK2oP8zqAP4LXF83u2d8fBizyuyO8ni51mMPXDKNrtjmzr6Ei0ov9anPc4CastdZEkiJ+85sTcD8Lp2o="
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: pyoceans/python-ctd
    tags: true
    all_branches: master
    condition: '$TRAVIS_JOB_NAME == "default"'