language: python

sudo: false

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.5
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  - python: 2.7
    env: TEST_TARGET=doctest
  - python: 3.6
    env: TEST_TARGET=doctest
  - python: 3.6
    env: TEST_TARGET=coding_standards

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
  - source activate TEST
  # GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install ctd-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      py.test -s -rxs -v tests ;
    fi

  - if [[ $TEST_TARGET == 'doctest' ]]; then
      py.test -s -rxs --doctest-modules -vv ctd ;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      flake8 --max-line-length=110 ctd ;
      flake8 --max-line-length=110 tests ;
    fi
