before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

language: python

matrix:
  fast_finish: true
  include:
    - name: "default"
      env: PY=3.7
    - name: "doctest"
      env: PY=3.7
    - name: "coding_standards"
      env: PY=3.7

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda --quiet
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
  - source activate TEST

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install ctd-${version}.tar.gz && popd

script:
  - if [[ $TRAVIS_JOB_NAME == "default" ]]; then
      pytest -n 2 -rxs --cov=ctd tests ;
    fi

  - if [[ $TRAVIS_JOB_NAME == "doctest" ]]; then
      pytest -s -rxs --doctest-modules -vv ctd ;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      pytest --flake8 -m flake8 ;
    fi
